apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-api
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: realtime-api
          image: gcr.io/PROJECT_ID/realtime-api:stable
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          env:
            - name: PROJECT_ID
              value: "PROJECT_ID"
            - name: REGION
              value: "us-central1"
